"""Build the English product, support and policy pages with the existing site theme."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1] / 'dist'
MAIL = 'weizhichao@qishanlabs.com'
EULA = 'https://www.apple.com/legal/internet-services/itunes/dev/stdeula/'

def section(n, title, body):
    return f'<section><h2><span>{n:02d}</span>{title}</h2>{body}</section>'

def page(route, title, lede, body, version=None):
    chinese = '/' + route + '/'
    canonical = 'https://qishanlabs.com/en/' + route + '/'
    meta = f'<div class="document-meta"><span>Version {version}</span><span>Effective: September 11, 2026</span><span>JotIt for iOS</span></div>' if version else ''
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#f7f7fc"><title>{escape(title)} | JotIt</title>
<meta name="description" content="{escape(lede, quote=True)}"><link rel="canonical" href="{canonical}">
<link rel="alternate" hreflang="en" href="{canonical}"><link rel="alternate" hreflang="zh-Hans" href="https://qishanlabs.com{chinese}">
<meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:title" content="{escape(title)} | JotIt"><meta property="og:url" content="{canonical}">
<link rel="icon" href="/assets/favicon-48.png"><link rel="stylesheet" href="/style.css?v=20260911-i18n"></head><body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header shell"><a class="brand" href="/en/products/jotit/" aria-label="JotIt home"><img class="brand-icon" src="/assets/app-icon-192.png" alt="" width="44" height="44"><span class="brand-copy"><strong>JotIt</strong><small>Plans and expenses, together</small></span></a>
<nav class="site-nav" aria-label="Main navigation"><a href="/en/products/jotit/">Product</a><a href="/en/privacy/">Privacy</a><a href="/en/support/">Support</a><a href="/en/terms/">Terms</a><a href="{chinese}" lang="zh-Hans" hreflang="zh-Hans">简体中文</a></nav></header>
<main id="main" class="shell page-main"><section class="document-hero"><p class="eyebrow">JotIt by Qishan Lab</p><h1>{escape(title)}</h1><p class="document-lede">{lede}</p>{meta}</section>{body}</main>
<footer class="site-footer"><div class="shell footer-grid"><div><strong>JotIt · Qishan Labs</strong><p>Shanghai Qishan Cultural Communication Co., Ltd.</p></div><nav aria-label="Footer navigation"><a href="/en/privacy/">Privacy</a><a href="/en/support/">Support</a><a href="/en/terms/">Terms</a><a href="mailto:{MAIL}">Contact</a></nav></div><div class="shell footer-bottom"><span>App filing: 沪ICP备2026044636号-1A</span><span>© 2026 上海祁杉文化传播有限公司</span></div></footer></body></html>'''
    dest = ROOT / 'en' / route / 'index.html'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html)

terms = [
('Terms and operator', f'<p>These terms apply to the JotIt iOS app. The operator is Shanghai Qishan Cultural Communication Co., Ltd. (上海祁杉文化传播有限公司), App filing 沪ICP备2026044636号-1A. Downloading, purchasing or using the app means you agree to these terms, our privacy policy and applicable Apple rules.</p><p>In addition to these product-specific terms, the app uses Apple’s <a href="{EULA}">Standard End User License Agreement (EULA)</a>. Mandatory Apple rules prevail in case of conflict.</p>'),
('Free credits and Pro', '<ul><li>New users receive 100 AI credits in total for the first 30 days after the first valid installation, not 100 per day.</li><li>After this introductory period, the free plan includes 60 AI credits per UTC calendar month.</li><li>Pro Monthly: the reference price in mainland China is CNY 18 per month, with 600 AI credits per subscription month.</li><li>Pro Annual: the reference price in mainland China is CNY 128 per year. Billing and renewal are annual; credits reset to 600 each month on a cycle anchored to the purchase date.</li></ul><p>The final price, currency, taxes and availability are shown on the App Store purchase screen. Unused credits do not roll over, cannot be redeemed for cash and cannot be transferred. After cancellation, access continues until the paid period ends, then the free allowance applies.</p>'),
('How AI credits are used', '<p>Credits are deducted only when a request actually enters our cloud AI service. Standard requests usually use 1 credit. Long text exceeding 8,000 input characters or complex analysis requiring a larger output budget uses 3 credits. The membership page shows the server-confirmed allowance, remaining balance and reset time.</p><p>Automatic network retries of the same request are not charged again. If a request reaches the AI service but an upstream timeout, network interruption or lost response prevents it from appearing on your device, consumed credits may not be returned. Contact support if problems persist.</p>'),
('Renewal, cancellation and refunds', '<p>Payment is charged to your Apple ID when you confirm the purchase. The subscription renews automatically unless canceled at least 24 hours before the current period ends; renewal charges are also billed through Apple. Manage or cancel in Me → Pro → Manage Subscription, or in iPhone Settings → Apple ID → Subscriptions.</p><p>On a replacement device, use the same Apple ID and choose Restore Purchases on the membership page. Apple handles refund requests and outcomes under its policies. Submit a request through <a href="https://reportaproblem.apple.com/">Apple’s Report a Problem page</a>.</p>'),
('Local features and AI results', '<p>Manual schedules, expenses, reminders, backup, restore and export remain available without a subscription or when AI credits run out. Online AI is an assistant and may omit or misunderstand information. Independently check important time, money, health, legal, financial or other decisions, and review suggestions before saving.</p>'),
('Acceptable use', '<p>Do not use the app for unlawful activity, infringement, interference with the service, bulk automated requests, bypassing credit or security checks, reselling the service, or accessing someone else’s data or entitlements. We may temporarily limit abnormal request rates and, for confirmed serious abuse, suspend relevant online capabilities and retain necessary records as required by law.</p>'),
('Service and terms updates', '<p>Future prices, allowances or rules may change because of model costs, service quality, legal requirements or product changes. Subscription price changes follow Apple’s notification and consent processes. We do not retroactively increase charges for a period already paid for. Material changes are reflected in the version and date on this page.</p>'),
('Contact', f'<p>For questions about subscriptions, credits, restored purchases or these terms, email <a href="mailto:{MAIL}">{MAIL}</a>. Include the app version, time of the issue and an Apple order number if necessary. Do not send passwords, verification codes or complete payment information.</p>')]
page('terms', 'Subscription & terms of use', 'Understand your free allowance, Pro billing, monthly credits, cancellation and refunds.', '<article class="document-card legal-copy">'+''.join(section(i,t,b) for i,(t,b) in enumerate(terms,1))+'</article>', '1.0')

privacy = [
('Scope and operator', '<p>This policy covers JotIt for iOS and its official privacy and support websites. The operator is Shanghai Qishan Cultural Communication Co., Ltd. (上海祁杉文化传播有限公司), App filing 沪ICP备2026044636号-1A. JotIt manages schedules, tasks and expenses and offers optional parsing and question-answering features. We process information for clear purposes, with data minimization, transparency and security.</p>'),
('Information we process', '<ul><li><strong>Schedules and reminders:</strong> titles, times, notes, repetition rules and reminder settings are processed and stored on your device to create, show, search and trigger reminders.</li><li><strong>Expenses and statistics:</strong> amounts, categories, dates and notes are processed and stored locally for recording, queries and totals.</li><li><strong>Profile:</strong> your chosen nickname and avatar are stored and displayed locally.</li><li><strong>Voice and image input:</strong> speech transcripts and text extracted from images create suggestions for schedules, expenses or queries. Recognition uses system or on-device capabilities. Original images are not uploaded.</li><li><strong>Online AI:</strong> text you submit, speech transcripts, OCR text and necessary summaries are sent over encrypted connections with your permission to parse requests and generate responses or suggestions.</li><li><strong>Subscriptions and credits:</strong> Apple-signed transaction proofs, product and original transaction identifiers, purchase and expiry dates, credit periods and usage counts are used to validate Pro, restore purchases and calculate balances. Apple handles payments. Proofs go to our private verification service, not to the AI model.</li><li><strong>Credits and security:</strong> App Attest identifiers and proofs, request digests, network addresses and results are used to verify the app and request integrity, share credit allowances, limit rates and prevent replay or abuse. The key identifier is stored in the device keychain. The server retains public keys, counters, attestation receipts and security records, not AI model input.</li></ul><p>No app account is required. We do not purchase personal information from contact lists, advertising platforms or data brokers.</p>'),
('System permissions', '<p>Notifications deliver reminders at your chosen times. Microphone and speech recognition permissions convert voice input into text. Camera and photo access support images you choose to recognize and content you choose to save. Permissions are requested when needed and can be withdrawn in iPhone Settings. Refusing a permission affects only the features that depend on it.</p>'),
('Optional online AI', '<p>Online AI is off by default. Only after you allow it and initiate a request does the app send necessary text over HTTPS. This may include submitted text, speech transcripts, on-device OCR text and summaries you permit, such as counts, category totals or records within a requested range. Original images are never sent to online AI. Analysis prefers aggregated summaries; record details are used only when you explicitly request them and only as needed.</p><p>Apple App Attest validates the app and request integrity. Registration and requests process random verification key identifiers, Apple-signed attestations, request digests, counters and network addresses for rate limits and replay and abuse prevention. These do not include your account, device name or advertising identifier, are not used for advertising tracking and are not sent to DeepSeek.</p><p>AI results may be inaccurate. The app labels AI-generated content. Check it before saving, sharing or acting on it.</p>'),
('Third-party services', '<p>Online parsing and analysis use the DeepSeek API. The corresponding registered generative AI service is 求索对话 DeepSeek Chat, filing Beijing-DeepseekChat-202404280016. Necessary text may be processed by that provider under its applicable privacy policy and terms. Enabling AI does not automatically upload your complete schedule database, complete expense database or original images.</p><p>App integrity checks use Apple App Attest. Registration connects to Apple’s attestation service. Device security hardware protects the private key, and our server checks Apple’s signed attestation.</p><p>Pro subscriptions and purchase restoration use Apple StoreKit. Apple handles purchases, charges, renewal and refunds. We do not receive full card numbers or Apple ID passwords. Apple-signed transaction proofs accompany App Attest-protected AI requests to our private verification service. It extracts only the necessary product and original transaction identifiers, purchase and expiry times, and revocation or upgrade status, then derives an irreversible subscription allowance identifier. Neither the proof nor these fields are sent to DeepSeek.</p><p>The app has no advertising SDK, does not track you across apps for advertising and does not sell personal information.</p>'),
('Storage, retention and security', '<p>Schedules, expenses, profiles, preferences and backups are primarily stored on your device. The operator does not create cloud copies of this local business data unless you initiate export or system backup features. Information for online AI, shared allowances and security is processed only as needed. We use access controls, transport encryption and data minimization. No internet service can guarantee absolute security. We handle incidents and required notifications according to applicable law.</p><p>Our server does not log AI prompts, response bodies or original images. Anonymous credit counts, request digests and duplicate-operation markers are kept for up to 45 days to support monthly allowance accuracy. Operational logs without message bodies are generally kept for 30 days. Signed transaction proofs are used in short-lived in-process verification caches and are not written to the credit database. App Attest public keys, counters and attestation receipts remain while the security verification system is in use, to validate later requests and prevent replay.</p><p>Deleting records, clearing local data or uninstalling removes relevant device data according to iOS behavior. You manage and delete exported backups yourself. Uninstalling or reinstalling does not automatically delete older server security records; old records cannot identify a new installation. Contact us about processing such records. Because the app has no account, we may be unable to locate or disclose an anonymous record if we cannot reliably establish that it belongs to you.</p>'),
('Your choices and rights', '<ul><li>View, correct or delete schedules, expenses, nicknames and avatars.</li><li>Export JSON, calendar or expense files and restore backups.</li><li>Clear AI conversations, disable online AI or local-data analysis.</li><li>Manage or cancel Pro in system subscription settings and restore valid purchases in the app.</li><li>Withdraw notification, microphone, speech recognition, camera or photo permissions.</li><li>Contact us with questions, complaints or requests under applicable law.</li></ul><p>Withdrawing consent does not affect processing already performed on the basis of prior consent. We verify necessary information and handle requests under applicable law.</p>'),
('Children', '<p>The app is not specifically designed for children. Children under 14 should use it with parental or guardian consent and guidance. Guardians who believe a child provided personal information without appropriate consent can contact us.</p>'),
('Website information', '<p>The privacy and support websites are static pages, without product analytics, advertising tracking or account login. Hosting providers may process routine network logs such as IP addresses, browser types and access times for operation and security, under their applicable terms.</p>'),
('Contact', f'<p>Operator: Shanghai Qishan Cultural Communication Co., Ltd. (上海祁杉文化传播有限公司).</p><p>Primary email: <a href="mailto:{MAIL}">{MAIL}</a>. Backup email: <a href="mailto:281916057@qq.com">281916057@qq.com</a>.</p>'),
('Policy updates', '<p>We update this policy and its version and date when features, processing or applicable rules change. We provide appropriate notice for material changes affecting your rights. If you disagree, you may stop using the relevant features or delete the app.</p>')]
page('privacy', 'Privacy policy', 'See what stays on your device, what optional online AI sends, and how you can control your information.', '<article class="document-card legal-copy">'+''.join(section(i,t,b) for i,(t,b) in enumerate(privacy,1))+'</article>', '1.9')

faqs = [
('Why did a reminder not appear?', 'Allow JotIt notifications in Settings. Check that the event has a future reminder time. Focus modes and notification summaries may delay delivery. Reopen JotIt and create a reminder a few minutes ahead to check.'),
('Voice input is unavailable or inaccurate', 'Allow microphone and speech recognition access under Settings → Privacy & Security. Speak clearly near the microphone with less background noise. Edit transcripts and suggestions before saving.'),
('Does image recognition upload my photo?', 'No. OCR runs on your device. Use a clear, correctly oriented image with complete text and allow camera or photo access as needed. If you enable online AI, necessary extracted text may be sent for a request you initiate.'),
('Online AI is unavailable', 'Check the network, the online AI setting and your balance in Me → Pro. Standard requests usually use 1 credit; long or complex requests use 3. When credits run out, wait for the next reset or upgrade. Rate limits or maintenance may temporarily affect availability. Local schedules, expenses, reminders and backups remain usable.'),
('What is included in the free and Pro plans?', 'New users receive 100 AI credits in total for 30 days, then 60 per UTC calendar month. Both Pro plans include 600 per subscription month. Monthly plans renew monthly. Annual plans are paid yearly, but credits reset monthly, not all at once for the year. Unused credits do not roll over. Local schedules, expenses, reminders, backup and export do not require Pro.'),
('How do I restore, cancel or manage my subscription?', 'Sign in to the device with the Apple ID used for purchase, then choose Restore Purchases in Me → Pro. Active members can use Manage Subscription on that page; you can also open iPhone Settings → Apple ID → Subscriptions. Cancel at least 24 hours before the period ends to prevent renewal. Access continues through the paid period. If a charged purchase does not restore, contact support with the purchase time and necessary Apple order number, not full payment details or passwords.'),
('How do I back up and restore?', 'Open Me → Data & Backup, export and keep the file in a safe place. Export the current data again before restoring. A restore can replace records; read the confirmation and selected scope carefully.'),
('How do I delete records or clear local data?', 'Delete individual schedules or expenses in their respective pages. Use the local-data clearing option in Data & Backup for a full reset. Export a backup first if needed; deletion may not be reversible.'),
('How do I move to a new phone?', 'Export a backup on the old device, transfer it securely and import it on the new device. Check records and notification permissions after import. Restore a valid Pro subscription using the same Apple ID. Subscription restoration does not restore your local records.'),
('The app crashes or looks wrong', 'Update to an available current version, restart the app and record the steps that caused the issue. Back up data before reinstalling. Contact support with the app version, iOS version, device model and reproduction steps.')]
support = '<section class="document-card legal-copy"><h2>Start with these checks</h2><ol><li>Use iOS 17 or later and the current available app version.</li><li>Restart the app and check connectivity for online AI.</li><li>Review notification, microphone, speech recognition, camera and photo permissions.</li></ol></section><section class="faq-section"><h2>Frequently asked questions</h2><div class="faq-list">'+''.join(f'<details><summary><span>{escape(q)}</span><i aria-hidden="true"></i></summary><div class="faq-answer"><p>{escape(a)}</p></div></details>' for q,a in faqs)+'</div></section>'+f'<section class="document-card legal-copy"><h2>Contact support</h2><p>Email <a href="mailto:{MAIL}?subject=JotIt%20Support">{MAIL}</a> with your app version, iOS version, iPhone model, issue and reproduction steps. Hide unrelated personal information in screenshots. Do not send passwords, verification codes, full identity documents or complete payment details.</p><p><a href="/en/terms/">Read subscription terms</a> · <a href="/en/privacy/">Read our privacy policy</a></p></section>'
page('support', 'Help with JotIt', 'Find answers about reminders, AI credits, purchases, backups and your data, or contact product support.', support)

product = '''<section class="document-card legal-copy"><h2>One sentence. Two things recorded.</h2><p>“Meeting tomorrow at 3 pm, lunch today cost 12 dollars.” JotIt turns your words into editable event and expense suggestions. Check the time, amount and details before saving.</p><p>Use text, system voice input or on-device image text recognition. Your schedules and expenses stay on your device by default; online AI is off until you choose to enable it.</p></section>
<section class="summary-grid" aria-label="Features"><article><strong>Capture together</strong><p>Turn a paragraph into several schedules or expense entries.</p></article><article><strong>See your day</strong><p>Calendars, tasks, reminders and recurring events in one place.</p></article><article><strong>Track expenses</strong><p>Record income and spending, then review category and monthly totals.</p></article><article><strong>Stay in control</strong><p>Review AI suggestions, export records and create local backups.</p></article></section>
<section class="document-card legal-copy"><h2>Start free. Add Pro when you need more AI.</h2><p>New users receive 100 AI credits for the first 30 days, then 60 per UTC calendar month. Both Pro plans include 600 per subscription month. Standard requests use 1 credit; long or complex requests use 3.</p><ul><li><strong>Pro Monthly:</strong> billed and renewed monthly.</li><li><strong>Pro Annual:</strong> billed and renewed yearly; credits reset monthly.</li><li>Unused credits do not roll over. Local schedules, expenses, reminders, backup, restore and export remain free.</li></ul><p>The reference prices in mainland China are CNY 18/month and CNY 128/year. Your actual local price and currency appear on the App Store purchase screen. Read the <a href="/en/terms/">subscription and cancellation terms</a>.</p></section>
<section class="trust-strip" aria-label="Product information"><div><strong>iOS 17+</strong><span>System requirement</span></div><div><strong>13 languages</strong><span>App interface</span></div><div><strong>No ad tracking</strong><span>Privacy</span></div><div><strong>No account</strong><span>Start on your device</span></div></section>
<section class="document-card legal-copy"><h2>Your data, your choice</h2><p>No app registration is required. Original images are not uploaded. Only necessary text is sent when you allow and initiate online AI. Check upcoming plans using widgets and Apple Watch, and manage exports and local backups from the app.</p><div class="button-row"><a class="button button-primary" href="/en/support/">Get support</a><a class="button button-secondary" href="/en/privacy/">Read privacy policy</a></div></section>'''
page('products/jotit', 'Plans and expenses, together.', 'Capture a thought, check the details and save. JotIt brings schedules, tasks and everyday spending into one app.', product)

for route in ['support','privacy','terms','products/jotit']:
    path=ROOT/route/'index.html'
    txt=path.read_text()
    switch=f'<a href="/en/{route}/" lang="en" hreflang="en">English</a>'
    if switch not in txt:
        pos=txt.index('</nav>')
        txt=txt[:pos]+switch+'\n    '+txt[pos:]
    if 'hreflang="en"' not in txt.split('</head>')[0]:
        txt=txt.replace('</head>',f'<link rel="alternate" hreflang="en" href="https://qishanlabs.com/en/{route}/">\n<link rel="alternate" hreflang="zh-Hans" href="https://qishanlabs.com/{route}/">\n</head>')
    if route=='products/jotit':
        txt=txt.replace('<strong>简体中文</strong><span>支持语言</span>','<strong>13 种语言</strong><span>App 界面语言</span>')
        if '按年扣款，积分按月恢复' not in txt:
            txt=txt.replace('  </main>','''    <section class="document-card legal-copy"><h2>免费开始，高频使用再升级。</h2><p>新用户前 30 天共有 100 AI 积分，之后每个 UTC 自然月 60 积分。Pro 月付和年付每订阅月均含 600 积分。普通请求消耗 1 积分，长文本或复杂分析消耗 3 积分。</p><p>中国大陆参考价：月付 ¥18/月，年付 ¥128/年。年付按年扣款，积分按月恢复，未使用积分不结转。相较连续 12 个月月付，年付少 ¥88（约省 41%）；其他地区以购买页实际价格为准。本地日程、记账、提醒、备份、恢复与导出始终免费使用。</p><p><a href="/terms/">查看自动续订、取消与恢复购买规则</a></p></section>
  </main>''')
    path.write_text(txt)

print('Built four English pages and added language links to four Chinese pages.')
